// Koder Remote Access — mobile-optimized single page, view + control
// (docs/research/10-remote-control.md, Phase B).
// Served as a plain string by remote-server.js (no separate static files,
// same "one self-contained response" discipline as extension.js's own
// html() method for the desktop webview). Renders the same event vocabulary
// panel.js already understands (chunk/thought/tool/toolUpdate/system/
// modeChanged), plus a composer (text input + send) and tappable
// Allow/Deny pills on a `permission` event — a phone-sized remote, not a
// full mobile IDE, but no longer read-only. Both POST to remote-server.js's
// `/control/send` and `/control/permission` routes, which forward straight
// into extension.js's `AgentViewProvider.onWebviewMessage` — the same
// dispatch the desktop composer/permission bar already drive.
//
// Built as string concatenation (not a template literal) deliberately: the
// embedded <script> needs to contain its own JS string/regex literals
// (including backtick-free markdown-fence matching), and keeping the whole
// page out of a `...` template literal avoids any risk of an inner token
// prematurely closing the outer one.
"use strict";

var CSS = [
  ":root {",
  "  --bg: #0e1116;",
  "  --fg: #c8cede;",
  "  --muted: #8a93a8;",
  "  --faint: #5c6577;",
  "  --accent: #7c5cff;",
  "  --accent-soft: rgba(124, 92, 255, 0.14);",
  "  --hairline: rgba(255, 255, 255, 0.08);",
  "  --mono: 'JetBrains Mono', 'SF Mono', Menlo, monospace;",
  "}",
  "* { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }",
  "html, body { height: 100%; margin: 0; padding: 0; background: var(--bg); color: var(--fg);",
  "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 15px; }",
  "#app { display: flex; flex-direction: column; min-height: 100vh;",
  "  padding-top: env(safe-area-inset-top); padding-bottom: env(safe-area-inset-bottom); }",
  "#header { display: flex; align-items: center; gap: 10px; padding: 14px 16px;",
  "  border-bottom: 1px solid var(--hairline); position: sticky; top: 0; background: var(--bg); z-index: 5; }",
  "#header .ws { font-weight: 600; font-size: 14px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  "#header .mode-badge { font-size: 11px; color: #c8b6ff; background: var(--accent-soft);",
  "  border-radius: 99px; padding: 3px 10px; margin-left: auto; text-transform: capitalize; }",
  "#dot { width: 8px; height: 8px; border-radius: 99px; background: #4ed8a2; flex: none; }",
  "#dot.reconnecting { background: #ffb454; animation: pulse 1s ease-in-out infinite; }",
  "#dot.lost { background: #ff6b81; }",
  "@keyframes pulse { 50% { opacity: 0.3; } }",
  "#banner { display: none; text-align: center; color: var(--faint); font-size: 12.5px; padding: 10px 16px;",
  "  border-bottom: 1px solid var(--hairline); }",
  "#banner.show { display: block; }",
  "#messages { flex: 1; overflow-y: auto; padding: 14px 14px 32px; display: flex; flex-direction: column; gap: 12px; }",
  ".msg { line-height: 1.55; white-space: pre-wrap; word-break: break-word; font-size: 14.5px; }",
  ".msg.user { align-self: flex-end; background: var(--accent-soft); border: 1px solid rgba(124,92,255,0.22);",
  "  border-radius: 14px 14px 4px 14px; padding: 10px 14px; max-width: 88%; }",
  ".msg.agent { padding: 0 2px; white-space: normal; }",
  ".msg.agent code { font-family: var(--mono); font-size: 13px; background: rgba(255,255,255,0.07);",
  "  border-radius: 4px; padding: 1px 5px; }",
  ".msg.agent pre { background: #0b0d12; border: 1px solid var(--hairline); border-radius: 8px; padding: 10px;",
  "  overflow-x: auto; font-family: var(--mono); font-size: 12.5px; white-space: pre; }",
  ".msg.system { color: var(--faint); font-size: 12px; text-align: center; }",
  ".tool { display: flex; align-items: center; gap: 8px; border-left: 2px solid var(--hairline); padding: 4px 10px;",
  "  font-size: 12.5px; color: var(--muted); }",
  ".tool .dot2 { width: 6px; height: 6px; border-radius: 99px; background: var(--accent); flex: none; }",
  ".tool.running .dot2 { animation: pulse 1.1s ease-in-out infinite; }",
  ".tool.done { border-left-color: rgba(78,216,162,0.4); }",
  ".tool.done .dot2 { background: #4ed8a2; }",
  ".tool.failed { border-left-color: rgba(255,107,129,0.4); }",
  ".tool.failed .dot2 { background: #ff6b81; }",
  ".tool .title { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: var(--mono); }",
  ".permbar { background: rgba(255,180,84,0.08); border: 1px solid rgba(255,180,84,0.28); border-radius: 10px;",
  "  padding: 12px 14px; font-size: 13px; }",
  ".permbar .ptitle { font-family: var(--mono); font-size: 12px; margin-bottom: 8px; color: var(--fg); }",
  ".permbar .pills { display: flex; gap: 8px; flex-wrap: wrap; }",
  ".permbar .pill { border-radius: 99px; padding: 7px 16px; font-size: 12.5px; background: rgba(255,255,255,0.08);",
  "  color: var(--fg); border: 1px solid var(--hairline); font-family: inherit; }",
  ".permbar .pill.allow { background: rgba(78,216,162,0.16); border-color: rgba(78,216,162,0.4); color: #7be0b8; }",
  ".permbar .pill.deny { background: rgba(255,107,129,0.14); border-color: rgba(255,107,129,0.36); color: #ff8fa0; }",
  ".permbar .pill:active { opacity: 0.6; }",
  ".permbar .pill:disabled { opacity: 0.4; }",
  ".permbar .caption { margin-top: 8px; color: var(--faint); font-size: 11.5px; }",
  ".empty { margin: auto; text-align: center; color: var(--muted); padding: 40px 24px; }",
  ".empty .title { font-weight: 600; font-size: 15px; color: var(--fg); margin-bottom: 6px; }",
  ".empty .hint { font-size: 12.5px; line-height: 1.5; }",
  "#reconnectScreen { display: none; margin: auto; text-align: center; color: var(--muted); padding: 40px 24px; }",
  "#reconnectScreen.show { display: block; }",
  "#reconnectScreen .title { color: var(--fg); font-weight: 600; margin-bottom: 8px; font-size: 15px; }",
  "#reconnectScreen .hint { font-size: 12.5px; line-height: 1.6; }",
  "#composer { display: flex; align-items: flex-end; gap: 8px; padding: 10px 12px; border-top: 1px solid var(--hairline);",
  "  position: sticky; bottom: 0; background: var(--bg); }",
  "#composerInput { flex: 1; resize: none; min-height: 20px; max-height: 120px; background: rgba(255,255,255,0.06);",
  "  border: 1px solid var(--hairline); border-radius: 10px; color: var(--fg); font: inherit; font-size: 14.5px;",
  "  padding: 9px 12px; line-height: 1.4; }",
  "#composerInput:disabled { opacity: 0.5; }",
  "#composerInput::placeholder { color: var(--faint); }",
  "#sendBtn { flex: none; background: var(--accent); color: #fff; border: none; border-radius: 10px; padding: 0 16px;",
  "  height: 38px; font-size: 13.5px; font-weight: 600; }",
  "#sendBtn:disabled { opacity: 0.4; }",
  "#composerNote { text-align: center; color: var(--faint); font-size: 11px; padding: 0 12px 6px; display: none; }",
  "#composerNote.show { display: block; }",
].join("\n");

// Client-side script, built without template literals or literal backticks
// (see file header) so it can be embedded in the outer HTML string safely.
var SCRIPT = [
  "(function () {",
  "  'use strict';",
  "  var FENCE = String.fromCharCode(96, 96, 96);",
  "  var TICK = String.fromCharCode(96);",
  "  var qs = new URLSearchParams(location.search);",
  "  var token = qs.get('token');",
  "  if (token) {",
  "    try { sessionStorage.setItem('koderRemoteToken', token); } catch (e) {}",
  "    if (window.history && history.replaceState) history.replaceState(null, '', location.pathname);",
  "  } else {",
  "    try { token = sessionStorage.getItem('koderRemoteToken'); } catch (e) {}",
  "  }",
  "",
  "  var messagesEl = document.getElementById('messages');",
  "  var dotEl = document.getElementById('dot');",
  "  var wsNameEl = document.getElementById('wsName');",
  "  var modeBadgeEl = document.getElementById('modeBadge');",
  "  var bannerEl = document.getElementById('banner');",
  "  var reconnectEl = document.getElementById('reconnectScreen');",
  "  var composerEl = document.getElementById('composer');",
  "  var inputEl = document.getElementById('composerInput');",
  "  var sendBtnEl = document.getElementById('sendBtn');",
  "  var noteEl = document.getElementById('composerNote');",
  "",
  "  function showReconnect() {",
  "    ['header', 'banner', 'messages', 'composer'].forEach(function (id) {",
  "      var el = document.getElementById(id);",
  "      if (el) el.style.display = 'none';",
  "    });",
  "    reconnectEl.className = 'show';",
  "  }",
  "",
  "  if (!token) { showReconnect(); return; }",
  "",
  "  var streamEl = null, streamRaw = '';",
  "  var tools = {};",
  "  var busy = false;",
  "",
  "  function note(text, ms) {",
  "    noteEl.textContent = text;",
  "    noteEl.className = 'show';",
  "    if (ms) setTimeout(function () { noteEl.className = ''; }, ms);",
  "  }",
  "  function setBusy(b) {",
  "    busy = b;",
  "    inputEl.disabled = b;",
  "    sendBtnEl.disabled = b;",
  "    if (b) note('Agent is working…'); else noteEl.className = '';",
  "  }",
  "  function controlPost(path, body) {",
  "    return fetch(path + '?token=' + encodeURIComponent(token), {",
  "      method: 'POST',",
  "      headers: { 'Content-Type': 'application/json' },",
  "      body: JSON.stringify(body),",
  "    });",
  "  }",
  "  function submitPrompt() {",
  "    var text = inputEl.value.trim();",
  "    if (!text || busy) return;",
  "    inputEl.value = '';",
  "    controlPost('/control/send', { text: text })",
  "      .then(function (r) {",
  "        if (r.status === 409) { inputEl.value = text; note('Agent is busy — try again in a moment.', 2500); return; }",
  "        if (!r.ok) { inputEl.value = text; note('Could not send — check your connection.', 2500); }",
  "      })",
  "      .catch(function () { inputEl.value = text; note('Could not send — check your connection.', 2500); });",
  "  }",
  "  sendBtnEl.addEventListener('click', submitPrompt);",
  "  inputEl.addEventListener('keydown', function (e) {",
  "    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitPrompt(); }",
  "  });",
  "",
  "  function escapeHtml(s) {",
  "    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
  "  }",
  "  function renderRich(raw) {",
  "    var s = escapeHtml(raw);",
  "    var fenceRe = new RegExp(FENCE + '([\\\\s\\\\S]*?)(' + FENCE + '|$)', 'g');",
  "    s = s.replace(fenceRe, function (_, code) { return '<pre>' + code.replace(/^\\w*\\n/, '') + '</pre>'; });",
  "    var tickRe = new RegExp(TICK + '([^' + TICK + '\\\\n]+)' + TICK, 'g');",
  "    s = s.replace(tickRe, '<code>$1</code>');",
  "    s = s.replace(/\\*\\*([^*\\n]+)\\*\\*/g, '<b>$1</b>');",
  "    return s;",
  "  }",
  "  function clearEmpty() {",
  "    var e = messagesEl.querySelector('.empty');",
  "    if (e) e.remove();",
  "  }",
  "  function scrollBottom() {",
  "    window.scrollTo(0, document.body.scrollHeight);",
  "  }",
  "  function addMsg(cls, text) {",
  "    clearEmpty();",
  "    var el = document.createElement('div');",
  "    el.className = 'msg ' + cls;",
  "    el.textContent = text;",
  "    messagesEl.appendChild(el);",
  "    scrollBottom();",
  "    return el;",
  "  }",
  "  function endStream() {",
  "    streamEl = null;",
  "    streamRaw = '';",
  "  }",
  "  function streamText(text) {",
  "    clearEmpty();",
  "    if (!streamEl) {",
  "      streamEl = document.createElement('div');",
  "      streamEl.className = 'msg agent';",
  "      messagesEl.appendChild(streamEl);",
  "      streamRaw = '';",
  "    }",
  "    streamRaw += text;",
  "    streamEl.innerHTML = renderRich(streamRaw);",
  "    scrollBottom();",
  "  }",
  "  function addTool(t) {",
  "    endStream();",
  "    clearEmpty();",
  "    var el = document.createElement('div');",
  "    el.className = 'tool running';",
  "    el.innerHTML = '<span class=\"dot2\"></span><span class=\"title\"></span>';",
  "    el.querySelector('.title').textContent = t.title;",
  "    messagesEl.appendChild(el);",
  "    tools[t.id] = el;",
  "    scrollBottom();",
  "  }",
  "  function respondPermission(id, optionId, wrap) {",
  "    wrap.querySelectorAll('.pill').forEach(function (p) { p.disabled = true; });",
  "    wrap.querySelector('.caption').textContent = 'Sent — resolving…';",
  "    controlPost('/control/permission', { id: id, optionId: optionId })",
  "      .then(function (r) {",
  "        if (!r.ok) { wrap.querySelector('.caption').textContent = 'Could not send — try again or use the IDE.'; ",
  "          wrap.querySelectorAll('.pill').forEach(function (p) { p.disabled = false; }); }",
  "      })",
  "      .catch(function () {",
  "        wrap.querySelector('.caption').textContent = 'Could not send — try again or use the IDE.';",
  "        wrap.querySelectorAll('.pill').forEach(function (p) { p.disabled = false; });",
  "      });",
  "  }",
  "  function showPermission(m) {",
  "    var wrap = document.createElement('div');",
  "    wrap.className = 'permbar';",
  "    wrap.setAttribute('data-perm-id', String(m.id));",
  "    wrap.innerHTML = '<div class=\"ptitle\"></div><div class=\"pills\"></div>' +",
  "      '<div class=\"caption\">Approve or deny here, or from the IDE — whichever happens first wins.</div>';",
  "    wrap.querySelector('.ptitle').textContent = m.title;",
  "    var pillsEl = wrap.querySelector('.pills');",
  "    (m.options || []).forEach(function (o) {",
  "      var b = document.createElement('button');",
  "      b.className = 'pill ' + (String(o.kind || '').indexOf('allow') === 0 ? 'allow' : 'deny');",
  "      b.textContent = o.name;",
  "      b.addEventListener('click', function () { respondPermission(m.id, o.id, wrap); });",
  "      pillsEl.appendChild(b);",
  "    });",
  "    messagesEl.appendChild(wrap);",
  "    scrollBottom();",
  "  }",
  "  function clearPermission(id) {",
  "    var el = messagesEl.querySelector('[data-perm-id=\"' + id + '\"]');",
  "    if (el) el.remove();",
  "  }",
  "",
  "  function applyEvent(m) {",
  "    switch (m.type) {",
  "      case 'user': addMsg('user', m.text); break;",
  "      case 'chunk': streamText(m.text); break;",
  "      case 'tool': addTool(m); break;",
  "      case 'toolUpdate': {",
  "        var el = tools[m.id];",
  "        if (el) el.className = 'tool ' + (m.status === 'completed' ? 'done' : m.status === 'failed' ? 'failed' : 'running');",
  "        break;",
  "      }",
  "      case 'system': endStream(); addMsg('system', m.text); break;",
  "      case 'modeChanged':",
  "        modeBadgeEl.textContent = m.mode;",
  "        if (m.auto) addMsg('system', 'Switched to ' + m.mode + ' mode.');",
  "        break;",
  "      case 'turnStart': endStream(); setBusy(true); break;",
  "      case 'turnEnd': endStream(); setBusy(false); break;",
  "      case 'permission': showPermission(m); break;",
  "      case 'permissionResolved': clearPermission(m.id); break;",
  "    }",
  "  }",
  "",
  "  function renderSnapshot(snap) {",
  "    wsNameEl.textContent = snap.workspace || 'Koder';",
  "    modeBadgeEl.textContent = snap.mode || 'review';",
  "    messagesEl.innerHTML = '';",
  "    tools = {};",
  "    endStream();",
  "    var events = snap.transcript || [];",
  "    if (!events.length) {",
  "      messagesEl.innerHTML = '<div class=\"empty\"><div class=\"title\">No activity yet</div>' +",
  "        '<div class=\"hint\">Live chat updates will appear here as soon as you send a message from the IDE.</div></div>';",
  "    } else {",
  "      events.forEach(applyEvent);",
  "    }",
  "  }",
  "",
  "  function setDot(state) {",
  "    dotEl.className = state === 'open' ? '' : state;",
  "  }",
  "",
  "  var firstOpen = true;",
  "  var noConnTimer = null;",
  "",
  "  function fetchState(onDone) {",
  "    fetch('/state?token=' + encodeURIComponent(token))",
  "      .then(function (r) {",
  "        if (r.status === 401) { showReconnect(); return null; }",
  "        if (!r.ok) throw new Error('state ' + r.status);",
  "        return r.json();",
  "      })",
  "      .then(function (snap) {",
  "        if (snap) renderSnapshot(snap);",
  "        if (onDone) onDone();",
  "      })",
  "      .catch(function () {",
  "        bannerEl.textContent = 'Could not reach Koder — check you are still on the same WiFi.';",
  "        bannerEl.className = 'show';",
  "      });",
  "  }",
  "",
  "  function connect() {",
  "    fetchState(function () {",
  "      var es = new EventSource('/events?token=' + encodeURIComponent(token));",
  "      es.onopen = function () {",
  "        setDot('open');",
  "        bannerEl.className = '';",
  "        clearTimeout(noConnTimer);",
  "        if (!firstOpen) fetchState();",
  "        firstOpen = false;",
  "      };",
  "      es.onerror = function () {",
  "        setDot('reconnecting');",
  "      };",
  "      es.onmessage = function (ev) {",
  "        try {",
  "          var m = JSON.parse(ev.data);",
  "          if (m.type === 'clear') {",
  "            messagesEl.innerHTML = '<div class=\"empty\"><div class=\"title\">Chat cleared</div>' +",
  "              '<div class=\"hint\">A new chat was started in the IDE.</div></div>';",
  "            tools = {}; endStream(); setBusy(false);",
  "            return;",
  "          }",
  "          if (m.type === 'replay') {",
  "            renderSnapshot({ workspace: wsNameEl.textContent, mode: modeBadgeEl.textContent, transcript: m.events });",
  "            return;",
  "          }",
  "          applyEvent(m);",
  "        } catch (e) {}",
  "      };",
  "    });",
  "  }",
  "",
  "  connect();",
  "  noConnTimer = setTimeout(function () {",
  "    if (dotEl.className !== '') {",
  "      bannerEl.textContent = 'No connection yet. On guest/hotel WiFi your phone and laptop may be isolated from each other.';",
  "      bannerEl.className = 'show';",
  "    }",
  "  }, 20000);",
  "})();",
].join("\n");

/** Full mobile-page HTML — self-contained, no external requests except this server's own /state and /events. */
function renderMobilePage() {
  return (
    "<!DOCTYPE html>\n" +
    '<html>\n<head>\n<meta charset="UTF-8">\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n' +
    "<title>Koder Remote</title>\n" +
    "<style>\n" + CSS + "\n</style>\n" +
    "</head>\n<body>\n" +
    '<div id="app">\n' +
    '  <div id="header">\n' +
    '    <span id="dot"></span>\n' +
    '    <span class="ws" id="wsName">Koder</span>\n' +
    '    <span class="mode-badge" id="modeBadge">review</span>\n' +
    "  </div>\n" +
    '  <div id="banner"></div>\n' +
    '  <div id="messages"><div class="empty"><div class="title">Connecting…</div>' +
    '<div class="hint">Loading the live chat feed.</div></div></div>\n' +
    '  <div id="reconnectScreen">\n' +
    '    <div class="title">Disconnected</div>\n' +
    '    <div class="hint">Remote Access was turned off in the IDE, or this link expired.<br>' +
    "Scan a new QR code from Koder to reconnect.</div>\n" +
    "  </div>\n" +
    '  <div id="composerNote"></div>\n' +
    '  <div id="composer">\n' +
    '    <textarea id="composerInput" rows="1" placeholder="Message Koder…"></textarea>\n' +
    '    <button id="sendBtn">Send</button>\n' +
    "  </div>\n" +
    "</div>\n" +
    "<script>\n" + SCRIPT + "\n</script>\n" +
    "</body>\n</html>\n"
  );
}

module.exports = { renderMobilePage };
